version: 2.1

orbs:
  apptest-ai: apptestai/android-app-test@volatile

jobs:
  build:
    docker:
      - image: circleci/android:api-29
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx1024m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb
    steps:
      - checkout
      - run:
          name: create keystore file, fill key
          command: |
            mkdir -p $HOME/.sign/
            CURPWD=$(pwd)
            echo "$SIGNING_KEY" | base64 --decode > keystore.jks
            echo "" > ~/.sign/signing.properties
            echo "keystore=${CURPWD}/keystore.jks" >> ~/.sign/signing.properties
            echo "store.pass=$KEY_STORE_PASSWORD" >> ~/.sign/signing.properties
            echo "key.alias=$ALIAS" >> ~/.sign/signing.properties
            echo "key.pass=$KEY_PASSWORD" >> ~/.sign/signing.properties
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Run build
          command: ./gradlew assembleRelease
      - apptest-ai/run-test:
          binary_path: "app/build/outputs/apk/prod/release/app-prod-release.apk"
          project_id: "1111"
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results
